### PR TITLE
fix multi-threading in packages (issue 119)

### LINKED ISSUE #119: Polyester.jl v0.7.6 breaks multi-threading in packages
With Polyester.jl v0.7.6, multi-threading via `@batch` does not work anymore in functions defined in packages. Consider the following MWE.

I created a simple package `WIP`:
```julia
shell> ls
Manifest.toml	Project.toml	src

shell> cat Project.toml
name = "WIP"
uuid = "6ae9e3f1-1701-4e5e-b44a-7ea0b7f9ae98"
authors = ["Hendrik Ranocha"]
version = "0.1.0"

[deps]
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"

shell> cat src/WIP.jl
module WIP

using Polyester: @batch

function inner!(dst)
    @batch for i in eachindex(dst)
        dst[i] = Threads.threadid()
    end
    return nothing
end

end # module WIP
```

Then, I get the following results when starting Julia as `julia --project=. --threads=4`:

```julia
julia> using WIP; using Polyester: @batch

julia> dst = zeros(Int, 100);

julia> function inner!(dst)
           @batch for i in eachindex(dst)
               dst[i] = Threads.threadid()
           end
           return nothing
       end
inner! (generic function with 1 method)

julia> function foo_main!(dst,  n)
           for _ in 1:n
               inner!(dst)
           end
       end
foo_main! (generic function with 1 method)

julia> foo_main!(dst, 10^5); sort!(unique(dst)) # fine
4-element Vector{Int64}:
 1
 2
 3
 4

julia> function foo_wip!(dst,  n)
           for _ in 1:n
               WIP.inner!(dst)
           end
       end
foo_wip! (generic function with 1 method)

julia> foo_wip!(dst, 10^5); sort!(unique(dst)) # bad
1-element Vector{Int64}:
 1
```

It's fine again if I define the function in a submodule of `Main` (continuing the example above):

```julia
julia> module Submodule

       using Polyester: @batch

       function inner!(dst)
           @batch for i in eachindex(dst)
               dst[i] = Threads.threadid()
           end
           return nothing
       end

       end
Main.Submodule

julia> function foo_submodule!(dst,  n)
           for _ in 1:n
               Submodule.inner!(dst)
           end
       end
foo_submodule! (generic function with 1 method)

julia> foo_submodule!(dst, 10^5); sort!(unique(dst)) # fine
4-element Vector{Int64}:
 1
 2
 3
 4
```

It also works as expected when downgrading Polyester.jl to v0.7.5.

I'm using Julia v1.9.3 on macOS (ARM CPU).

CC @efaulhaber

### PR DESCRIPTION
**Pull request by ranocha**
Fix #119 

I don't know a good way to test this in CI. Do you have a suggestion, @chriselrod?

### CODE REVIEW

**Comment by chriselrod** [comment]
> Fix #119 
> 
> I don't know a good way to test this in CI. Do you have a suggestion, @chriselrod?

Does the example from #119 work for a test?

**Comment by ranocha** [comment]
The problem is that I would need to create a package that gets precompiled. I don't know how to do this in a sane way for CI and local testing. However, I added a test checking whether the code generated by `@batch` contains a call to `Base.Threads.nthreads` (which was called at macro-expansion time before, inserting the number of threads used by the process precompiling the package before).

**Comment by chriselrod** [comment]
Thanks for the fix!

**Comment by ranocha** [comment]
Thanks for reviewing it so quickly!

**Pull request merged**
