### PR TITLE
Remove ForwardDiff portion

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
I was profiling Requires.jl times by hand by commenting out repo by repo (https://discourse.julialang.org/t/profiling-requires-jl/73570), and low and behold a found a little 0.4 second gem. This is triggered by almost every downstream repo, since everything uses ForwardDiff, but isn't documented or used downstream. So... bye bye.

But wait, there's more! If you except this order within the next year, we will throw in a free repo! Did you hear free? That's because it's true. There's a whole repo just waiting. Accept our offer today.

https://github.com/ChrisRackauckas/PolyesterForwardDiff

### CODE REVIEW

**Comment by chriselrod** [comment]
This is a breaking change, so bump the version to 0.6?

**Comment by chriselrod** [comment]
Mind deleting the ForwardDiff code? That should get the codecov/project to pass, letting it merge.
Otherwise, I'll have to change the repo settings to let me override.

Another alternative would be to just take on a ForwardDiff dependency.
Or maybe create a separate repo for it.
Is @alanderos91 still using it?

**Comment by ChrisRackauckas** [comment]
I already made the separate repo. @alanderos91 can use that. We can move that to JuliaSIMD if you want.

**Comment by chriselrod** [comment]
> I already made the separate repo. @alanderos91 can use that. We can move that to JuliaSIMD if you want.

Is it at SciML now? That's fine, too.

Apparently I can override. I just had to turn off automerge to do it.

**Pull request merged**
